name: Tweet New Release

# Controls when the action will run. 
on:
  # Triggers the workflow on release
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 latest-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: fetch-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: johnPierson
          repo: MonocleForDynamo
      - name: Consume 
        run: |
          echo ${{ steps.fetch-latest-release.outputs.release }}
      - uses: captradeoff/x-post-action@v1.2
        with:
          message: "New Monocle for #DynamoBIM Release: https://github.com/johnpierson/MonocleForDynamo/releases/tag/${{ steps.fetch-latest-release.outputs.release }}" 
          appKey: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          appSecret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          accessToken: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          accessSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
