//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonocleViewExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonocleViewExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about monocle.
        /// </summary>
        public static string AboutMenuItemHeader {
            get {
                return ResourceManager.GetString("AboutMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about monocle | Update Available! v..
        /// </summary>
        public static string AboutMenuItemUpdateHeader {
            get {
                return ResourceManager.GetString("AboutMenuItemUpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new monocle update available. Please update via the package manager..
        /// </summary>
        public static string AboutMenuItemUpdateTooltip {
            get {
                return ResourceManager.GetString("AboutMenuItemUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better Save (ᵇʳᵒᵘᵍʰᵗ ᵗᵒ ʸᵒᵘ ᵇʸ ᵐᵒⁿᵒᶜˡᵉ™️).
        /// </summary>
        public static string BetterSaveFlyoutHeader {
            get {
                return ResourceManager.GetString("BetterSaveFlyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better save options. Because you deserve it. Brought to you by monocle™️.
        /// </summary>
        public static string BetterSaveFlyoutTooltip {
            get {
                return ResourceManager.GetString("BetterSaveFlyoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable FOCA.
        /// </summary>
        public static string FocaMenuItemHeader {
            get {
                return ResourceManager.GetString("FocaMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOCA, formerly known as the &quot;in-canvas align widget&quot;, is the cleaner of your dynamo graphs. this feature includes alignment tools, grouping tools and more..
        /// </summary>
        public static string FocaMenuItemTooltip {
            get {
                return ResourceManager.GetString("FocaMenuItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard group creation.
        /// </summary>
        public static string FocaStandardGroupMenuItemHeader {
            get {
                return ResourceManager.GetString("FocaStandardGroupMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graph resizerer.
        /// </summary>
        public static string GraphResizererMenuItemHeader {
            get {
                return ResourceManager.GetString("GraphResizererMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable highlighting.
        /// </summary>
        public static string HighlightDisableMenuItemHeader {
            get {
                return ResourceManager.GetString("HighlightDisableMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable highlighting.
        /// </summary>
        public static string HighlightEnableMenuItemHeader {
            get {
                return ResourceManager.GetString("HighlightEnableMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega input identifier.
        /// </summary>
        public static string MegaInputIdentifierMenuItem {
            get {
                return ResourceManager.GetString("MegaInputIdentifierMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node identifiers.
        /// </summary>
        public static string NodeIndentifierMenuItemHeader {
            get {
                return ResourceManager.GetString("NodeIndentifierMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node swapper.
        /// </summary>
        public static string NodeSwapperMenuItemHeader {
            get {
                return ResourceManager.GetString("NodeSwapperMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a node to use as a replacement.
        /// </summary>
        public static string NodeSwapperStatusMessageSelectReplacement {
            get {
                return ResourceManager.GetString("NodeSwapperStatusMessageSelectReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now select the nodes to match to the target node you selected..
        /// </summary>
        public static string NodeSwapperStatusMessageSelectToReplace {
            get {
                return ResourceManager.GetString("NodeSwapperStatusMessageSelectToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package usage boring mode.
        /// </summary>
        public static string PackageUsageBoringMenuItemHeader {
            get {
                return ResourceManager.GetString("PackageUsageBoringMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package usage doge.
        /// </summary>
        public static string PackageUsageDogeMenuItemHeader {
            get {
                return ResourceManager.GetString("PackageUsageDogeMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package usage.
        /// </summary>
        public static string PackageUsageMenuItemHeader {
            get {
                return ResourceManager.GetString("PackageUsageMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Save.
        /// </summary>
        public static string QuickSaveMenuItemHeader {
            get {
                return ResourceManager.GetString("QuickSaveMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + S.
        /// </summary>
        public static string QuickSaveMenuItemKeyboardShortcut {
            get {
                return ResourceManager.GetString("QuickSaveMenuItemKeyboardShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a quick date/time stamped &quot;snapshot&quot; of the current file..
        /// </summary>
        public static string QuickSaveMenuItemTooltip {
            get {
                return ResourceManager.GetString("QuickSaveMenuItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load settings from path.
        /// </summary>
        public static string SettingsLoadMenuItemHeader {
            get {
                return ResourceManager.GetString("SettingsLoadMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monocle settings.
        /// </summary>
        public static string SettingsMenuItemHeader {
            get {
                return ResourceManager.GetString("SettingsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore default settings.
        /// </summary>
        public static string SettingsRestoreMenuItemHeader {
            get {
                return ResourceManager.GetString("SettingsRestoreMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save current settings to default path.
        /// </summary>
        public static string SettingsSaveMenuItemHeader {
            get {
                return ResourceManager.GetString("SettingsSaveMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simple search.
        /// </summary>
        public static string SimpleSearchMenuItemHeader {
            get {
                return ResourceManager.GetString("SimpleSearchMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloppy Save.
        /// </summary>
        public static string SloppySaveMenuItemHeader {
            get {
                return ResourceManager.GetString("SloppySaveMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly save your file to your desktop, because you knew you were going to anyway..
        /// </summary>
        public static string SloppySaveMenuItemTooltip {
            get {
                return ResourceManager.GetString("SloppySaveMenuItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sloppy save to desktop.
        /// </summary>
        public static string SloppySaveMessageBoxCaption {
            get {
                return ResourceManager.GetString("SloppySaveMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sloppy save file?.
        /// </summary>
        public static string SloppySaveMessageBoxTitle {
            get {
                return ResourceManager.GetString("SloppySaveMessageBoxTitle", resourceCulture);
            }
        }
    }
}
