//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonocleViewExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonocleViewExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better Save (ᵇʳᵒᵘᵍʰᵗ ᵗᵒ ʸᵒᵘ ᵇʸ ᵐᵒⁿᵒᶜˡᵉ™️).
        /// </summary>
        internal static string BetterSaveFlyoutHeader {
            get {
                return ResourceManager.GetString("BetterSaveFlyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better save options. Because you deserve it. Brought to you by monocle™️.
        /// </summary>
        internal static string BetterSaveFlyoutTooltip {
            get {
                return ResourceManager.GetString("BetterSaveFlyoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Save.
        /// </summary>
        internal static string QuickSaveMenuItemHeader {
            get {
                return ResourceManager.GetString("QuickSaveMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + S.
        /// </summary>
        internal static string QuickSaveMenuItemKeyboardShortcut {
            get {
                return ResourceManager.GetString("QuickSaveMenuItemKeyboardShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a quick date/time stamped &quot;snapshot&quot; of the current file..
        /// </summary>
        internal static string QuickSaveMenuItemTooltip {
            get {
                return ResourceManager.GetString("QuickSaveMenuItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloppy Save.
        /// </summary>
        internal static string SloppySaveMenuItemHeader {
            get {
                return ResourceManager.GetString("SloppySaveMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly save your file to your desktop, because you knew you were going to anyway..
        /// </summary>
        internal static string SloppySaveMenuItemTooltip {
            get {
                return ResourceManager.GetString("SloppySaveMenuItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sloppy save to desktop.
        /// </summary>
        internal static string SloppySaveMessageBoxCaption {
            get {
                return ResourceManager.GetString("SloppySaveMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sloppy save file?.
        /// </summary>
        internal static string SloppySaveMessageBoxTitle {
            get {
                return ResourceManager.GetString("SloppySaveMessageBoxTitle", resourceCulture);
            }
        }
    }
}
